name: SimpleEnderButt
version: '1.0'
main: dev.vulpine.simpleEnderButt.SimpleEnderButt
api-version: '1.18'
authors: [ VulpineFriend87 ]
website: https://vulpine.top

commands:
  simpleenderbutt:
    aliases: [seb, enderbutt, eb, senderbutt, simpleeb, senderb]